# Site settings
title: Blog title
email: email@email.com
description: >
  This is the description.
baseurl: ''
url: ''

# Build settings
markdown: kramdown
paginate: 4
paginate_path: '/page:num/'
permalink: /:title/
gems: [jekyll-paginate]
highlighter: rouge
